import useStyles from "./styles";
import NavAppBar from "../../components/appbar";
import GalleryComponent from  '../../components/gallery';
import teamWork from '../../assets/img/teamWork2.png';

export default function Statistics() {
  const classes = useStyles();

  return (
    <div>
      <NavAppBar />
      <div>
        <div className={classes.body}>
          <div  className={classes.container}>
            <div className={classes.textDiv}>
              <span className={classes.title}>Python Module Statistics</span>
              <br />
              <span className={classes.text}>
                Here are some statistics collected.</span> <br/>
              <span className={classes.text}>
                Part of them were obtained manually based on the report generated by the PySniffer tool.
              </span> <br/>
              <span className={classes.textHint}>
                Click on the graph to expand it.
              </span>
            </div>             
            <div>
              <img src={teamWork} width="350px"/>
            </div>            
          </div>
            <GalleryComponent></GalleryComponent>
        </div>
      </div>
    </div>
  );
}
