import React, { useEffect, useState } from "react";
import useStyles from "./styles";
import NavAppBar from "../../components/appbar";
import { VictoryChart, VictoryBar, VictoryAxis, VictoryPie } from "victory";
import libs from '../../data/libs.json';
import libsPy from '../../data/libs_Py.json';
import GalleryComponent from  '../../components/gallery';
interface chartBar {
  x: string;
  y: number;
  color: string;
}

export default function Statistics() {
  const classes = useStyles();

  const [hovered, setHovered] = React.useState(false);

  useEffect(() => {
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const [top10, setTop10] = useState([]);
  const [top10Py, setTop10Py] = useState([]);

  const colors = [
    "darkred",
    "firebrick",
    "indianred",
    "tomato",
    "coral",
    "salmon",
    "darksalmon",
    "lightsalmon",
    "sandybrown",
    "peachpuff",
  ];

  useEffect(() => {
    //setTop10Py(getTop10(libsPy));
    //setTop10(getTop10(libs));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  /*const getTop10 = (libsList) => {
    var list = sortList(libsList);
    list.reverse();
    list = list.slice(0, 10);
    var bars: any = [];
    var i = 0;
    list.forEach((element) => {
      var bar: chartBar = {
        x: element.name,
        y: element.amount,
        color: colors[i],
      };
      bars.push(bar);
      i++;
    });
    return bars.reverse();
  };*/

  const sortList = (list: any) => {
    return list.sort((first: any, second: any) =>
      first.amount - second.amount  
    );
  };

  return (
    <div>
      <NavAppBar />
      <div
        className={classes.background}
      >
        <div className={classes.body}>
          <div>
            <div className={classes.textDiv}>
              <span className={classes.title}>Python Module Statistics</span>
              <br />
              <span className={classes.text}>
                Here are some statistics collected.</span> <br/>
                <span className={classes.text}>
                Part of them were obtained manually based on the report generated by the PySniffer tool.
              </span>
            </div>
            <GalleryComponent></GalleryComponent>
          </div>
        </div>
      </div>
    </div>
  );
}
